# Takes a secondary structure file generated by RNAVIEW and formats it according to the format required by ARTS.

import sys

secondary_struct_file = sys.argv[1]

file_lines = []


with open(secondary_struct_file, "r") as f:
    file_lines = f.readlines()

base_pair_lines = []

# Extracts the lines relative to 2D structure base pairings from the given 2D structure file
for i in range (0,len(file_lines)):
    if(file_lines[i] == "BEGIN_base-pair\n"):
        for j in range(i+1, len(file_lines)):
            if(file_lines[j] == "END_base-pair\n"):
                break
            base_pair_lines.append(file_lines[j])

formatted_lines = []

for line in base_pair_lines:
    splitted_line = line.split(" ")
    line_elements = []

    for elem in splitted_line:
        if(elem != ""):
          line_elements.append(elem)
    pair_string = (line_elements[1] + line_elements[2] + "-" + line_elements[1] + line_elements[4] + "\n")
    formatted_lines.append(pair_string)

pdb_name = secondary_struct_file[0:len(secondary_struct_file) - 8]

with open(pdb_name + ".pairs", "w") as p:
    p.writelines(formatted_lines)